// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/idcard-ui/DarkStudio.tsx": () => import("../components/mockups/idcard-ui/DarkStudio.tsx"),
  "./components/mockups/idcard-ui/PolishedPro.tsx": () => import("../components/mockups/idcard-ui/PolishedPro.tsx")
};
